pipeline {
  agent {
    docker {
      image 'axelav95/maven-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  tools {
        jdk 'Java 17'  // Asegúrate de que 'Java 17' sea el nombre que configuraste en Jenkins
  }
   environment {
        JAVA_HOME = tool 'Java 17'
    }
  stages {

    stage('Check Java Version') {
            steps {
                sh 'echo $JAVA_HOME'
                sh 'java -version'
            }
        }
    
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/AxelAV95/CICDLab.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'       
        // build the project and create a JAR file
        sh 'cd simple-app-cicd && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://34.201.116.83:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd CICDLab/simple-app-cicd && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "axelav95/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "CICDLab/simple-app-cicd/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd CICDLab/simple-app-cicd && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "CICDLab"
            GIT_USER_NAME = "AxelAV95"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "villalobos.axel@yahoo.es"
                    git config user.name "AxelAV95"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" CICDLab/simple-app-cicd-manifests/deployment.yml
                    git add CICDLab/simple-app-cicd-manifests/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
    }
  }
}
